;; -*- no-byte-compile: t; -*-
;;; ~/.doom.d/packages.el

(package! rvm)
(package! helm-dash)
(package! avy)
(package! coffee-mode)
(package! auto-dictionary)
(package! yasnippet-snippets)
(package! multiple-cursors)
(package! git-link)
(package! ggtags)
(package! flx)
(package! tss)
(package! tide)
(package! typescript-mode)
(package! deadgrep)
;; DAP mode
;; (package! dap-mode)
;; (package! lsp-mode)
;; (package! lsp-ui)
;; (package! company-lsp)
;; (package! evil-string-inflection)
;; (package! evil-collection)
;; (package! evil-magit)
(package! feature-mode)
(package! ember-mode)
(package! easy-kill)
