;; -*- no-byte-compile: t; -*-
;;; ~/.doom.d/packages.el

(package! auto-dictionary)
(package! counsel-dash)
(package! deadgrep)
(package! flycheck-clojure)
(package! flycheck-pos-tip)
(package! flx)
(package! ggtags)
(package! git-link)
(package! json-mode)
(package! multiple-cursors)
(package! org-jira)
(package! rvm)
(package! tide)
(package! tss)
(package! typescript-mode)
(package! web-beautify)
(package! yasnippet-snippets)
