;; -*- no-byte-compile: t; -*-
;;; ~/.doom.d/packages.el

(package! rvm)
(package! auto-dictionary)
(package! yasnippet-snippets)
(package! multiple-cursors)
(package! git-link)
(package! ggtags)
(package! flx)
(package! tss)
(package! tide)
(package! typescript-mode)
(package! deadgrep)
(package! feature-mode)
(package! ember-mode)
(package! easy-kill)
(package! pretty-mode)
(package! try)
(package! org-jira)
(package! rinari)
(package! web-beautify)
(package! json-mode)
;; (package! lsp-treemacs)
;; (package! highlight-symbol
;; :pin "7a789c779648c55b16e43278e51be5898c121b3a")
